== Selección de la Vida de Joseph Pike

Es mi deber dar cuenta de mis viajes espirituales y de los diversos ejercicios
del alma por los que he pasado y experimentado en el camino de regeneración,
desde mi juventud en adelante.
Aunque estas experiencias quedaron muy impresas en mi mente por la profunda aflicción,
tanto que no las olvidaré mientras perdure mi memoria,
han sido avivadas a menudo en mi recuerdo (por el
mismo Espíritu que me llevó a través de ellas),
junto con un sentido de apremio de consignar algunas de ellas por escrito.
Por tanto, esperé el tiempo del Señor para ser asistido en esto por el Santo Recordador,
para que lo que escribiera,
fuera en el sentido vivo y divino de lo que experimenté en tiempos pasados.
Al esperar,
encontré una dulce claridad para proceder y fui impulsado
a una divina evocación de las maravillosas misericordias,
liberaciones e indescriptibles bondades del Señor hacia mí, desde mi niñez hasta hoy.
Por tanto,
con gran reverencia se inclina humildemente mi alma
delante de Él (como con mi boca en el polvo),
alabando Su santo y eterno nombre,
y suplicándole que misericordiosamente se complazca
en guardarme y preservarme hasta el fin de mis días,
y me dé herencia eterna entre los santificados en nuestro Señor y Salvador Jesucristo.
Amén, dice mi alma.

Antes de cumplir los siete años,
el Espíritu del Señor empezó a obrar en mi mente y a luchar
conmigo para alejarme de los juegos y vanidades infantiles.
Esta santa Luz en mi alma (como descubrí poco después), me convencía que no debía ceder,
o hacer esto o aquello que se presentaba.
Y cuando en algún momento yo hacía lo que no debía haber hecho,
Ella traía aflicción y condenación sobre mí,
incluso en aquellos primeros años (como siempre ha hecho desde entonces),
cuando hacía algo que ofendía al Señor. Si este fuera el lugar apropiado para esto,
yo podría extenderme ampliamente sobre la naturaleza divina de
este santo principio de la Luz y Espíritu de Jesucristo en el alma,
de lo que las Santas Escrituras largamente testifican.
Sin embargo, seré guiado a hacerlo en el proceso de esta historia,
sabiendo por experiencia propia, que esta Luz no es algo de nuestra naturaleza,
ni algún conocimiento innato de nuestras mentes,
pues nada de nuestra naturaleza caída o que proceda de ella,
puede mostrarnos o convencernos de pecado.

Aunque en ese momento no sabía que era el Espíritu del Señor al que yo sentía
obrando en mí (tal como Samuel no conocía la voz del Señor cuando era un niño),
aún así era convencido en mí mismo, mediante Sus santas convicciones,
de que no debía hacer aquellas cosas que traían aflicción sobre mí. Cuando
en algún momento me abstenía de hacer lo que causaba dicha angustia,
experimentaba una dulce paz y satisfacción en la mente,
que me hacían estar más atento a Sus dictados,
y era alejado de muchos actos infantiles a los que los jóvenes son propensos.
De esta manera, crecí en sobriedad más allá de muchos de mi edad,
hasta aproximadamente los nueve años.

Pero poco tiempo después,
gradualmente comencé a perder esta condición. Recuerdo bien
la manera en que el enemigo de mi alma trabajó en secreto,
insinuando en mi mente:
"`¿Qué daño hacen o qué de malo hay en las cosas que son consideradas diversiones inocentes?`"
Al ser de un carácter vivaz y activo este cebo me capturó,
y mi mente dejó de prestarles atención a las convicciones
del Espíritu Santo del Señor en mi corazón,
lo que a menudo trajo angustia y condenación sobre mí. Al comenzar a amar los pasatiempos,
perdí la dulzura y la paz internas que antes había disfrutado,
y por el esfuerzo que hacía para sofocar las reprimendas secretas, me fui endureciendo,
hasta que por el deseo de seguir acompañado de otros muchachos indomables,
me deleitaba salir a las calles a jugar con ellos.
Como resultado de esto, me volví muy desenfrenado,
aunque mis queridos padres se esforzaban por restringirme.
Después de que pasaba tiempo con tales compañeros, cuando me quedaba un poco quieto,
los juicios del Señor se apoderaban de mí y me llevaban bajo gran aflicción de alma.
Entonces decidía abstenerme y no volver a hacerlo, sin embargo,
no podía resistir la siguiente tentación que se presentaba
y caía de nuevo en la misma trampa.

Así sucedió conmigo hasta que tuve aproximadamente doce años. Aunque,
para alabanza del Señor fui preservado de actos muy malos y desagradables, o incluso,
de palabras muy malas, mi mente fue alejada hacia vanidades y desenfreno,
y quedé lejos de ser tan sobrio como debía haber sido.

Aquí, si se me permite,
voy a hacer un paréntesis de advertencia con respecto a los padres:
Si ustedes tienen alguna estima por el bien de sus hijos,
deben mantener una mano muy estricta sobre ellos,
especialmente cuando son propensos al desenfreno, como lo era yo,
porque si mis padres no hubieran sido cuidadosos conmigo,
yo habría sido mucho peor de lo que fui.
Aunque mi querida madre nunca me consintió ninguna
práctica malvada (al ser una mujer prudente y discreta),
me amaba muchísimo, lo que yo sabía bien,
y confiando en alguna medida en esto a veces me aventuraba a salir,
lo cual no habría hecho si ella me hubiera corregido más a menudo.
Yo les aconsejaría y advertiría a todos los padres,
que tengan particular cuidado con sus hijos cuando van y regresan de la escuela,
para que no caigan en compañías que con seguridad los corromperán.
Puedo decir a partir de mi propia experiencia,
que si desde el principio se le dan cabida a cositas dañinas,
el enemigo toma ventaja y se va robando la mente
y alejándola gradualmente hacia mayores maldades.
Es por esta razón que se nos ordena que nos abstengamos de toda aparición del mal,
lo cual ciertamente no podemos hacer,
excepto con la asistencia del Espíritu Santo del Señor. Sin embargo,
al tomar la cruz de Cristo contra tales apariciones,
realmente experimentamos la derrota de los asaltos y tentaciones de Satanás.

Vi en la luz que si yo persistía en la vanidad y desenfreno,
permanecía en el camino de destrucción. Siempre que
los terrores del Señor estaban sobre mí,
nuevamente determinaba abstenerme y evitar tal conducta,
pero dichas decisiones eran hechas en mi propia fuerza y por eso quedaban en nada,
y a menudo la siguiente tentación prevalecía sobre mí. Entonces, una vez más,
los justos juicios del Señor se apoderaban de mí, y así repetidamente,
acumulaba más por lo que tenía que arrepentirme.

En ese tiempo, 1669,
no teníamos reuniones en la tarde en el lugar donde
eran celebradas las reuniones de culto público,
pero teníamos reuniones en la noche,
las cuales eran celebradas en las casas de los Amigos alternadamente.
William Edmundson de Rosenallis,^
footnote:[William Edmundson (1627-1712) fue un ministro y anciano
altamente estimado en la Sociedad de Amigos de Irlanda.
Él viajó y predicó incansablemente por más de cincuenta años,
y sufrió mucho por su testimonio de la verdad.]
ese digno y honorable Amigo y padre en Israel,
estaba interesado por ese tiempo en visitar a los Amigos de esta provincia.
Mientras él estaba en Cork,
la reunión de la noche tocaba celebrarla en la casa de la viuda
Bridget Denis (quien más tarde se convirtió en una Amiga fiel,
y hacia el final de su vida predicaba la verdad,
y no tengo duda de que murió en el Señor).
Yo fui a esa reunión con gran pesadez y aflicción sobre mi alma,
bajo un sentimiento triste por mis repetidas transgresiones contra el Señor,
y con fervientes clamores de que Él se complaciera en perdonarme
y me concediera poder y fuerza sobre las tentaciones del enemigo,
pues claramente vi que no era capaz, mediante ninguna habilidad propia,
de preservarme de la menor maldad,
en concordancia con lo dicho por nuestro bendito Señor:
"`Porque separados de mí nada podéis hacer.`"

Me senté en la reunión lleno de aflicción,
y el testimonio de William Edmundson alcanzó mi condición
interna y penetró mi alma tanto,
que no podía evitar gritar en la reunión bajo la consciencia
de mis pecados y por los terrores y juicios del Señor,
los cuales sentí más allá de lo que nunca antes había experimentado.
En ese momento fui tan verdaderamente bautizado por la poderosa
predicación de la Palabra de vida por medio de él,
como lo fueron aquellos a quienes el apóstol Pedro les predicó en Hechos 2:37. Entonces,
oh entonces,
mis pecados (y la verdadera pecaminosidad de ellos) fueron puestos delante de mí,
y en la agonía y amargura de mi alma secretamente clamé con humildes
oraciones al Señor por el perdón y remisión de ellos,
pidiéndole que por medio de Su Santo Espíritu se complaciera en permitirme
caminar más prudentemente en el porvenir y hacer Su santa voluntad,
para que yo pudiera servirle y adorarlo verdaderamente en Espíritu y en verdad.

Los pesados juicios del Señor continuaron sobre mí por un tiempo considerable, cuánto,
no lo recuerdo con exactitud, pero creo que fueron algunos meses,
hasta que llegué a obedecer Su divina luz o buen Espíritu en mi alma,
sin el cual no podría realizar algo aceptable para Dios.
He descubierto desde entonces mediante vívida experiencia,
que aunque nuestro Señor y Salvador Jesucristo (por medio de Sus sufrimientos y muerte)
me colocó a mí y a toda la humanidad en una condición adecuada para alcanzar la salvación,
aun así,
el cumplimiento de la misma es experimentado en nuestra obediencia a Su Santo Espíritu.
Él nos ha dado a cada uno de nosotros una medida de este Espíritu, según las Escrituras,
"`para provecho,`" y para que de esa manera nos '`ocupemos de nuestra salvación.`'

Después de que el poder bautizador del Señor se apoderó de mí,
me fue dado dominio sobre aquellas tentaciones que
antes habían prevalecido tan a menudo sobre mí,
y me volví más tranquilo en espíritu y tenía gran dulzura y consuelo.
Mis compañeros se preguntaban sobre este cambio,
y cuando me cruzaba con ellos en la calle los oía hablar entre sí:
"`¿Qué le pasa a Joe Pike?
¡No quiere hablarnos!`"
Al oír esto yo me regocijaba grandemente en mi corazón,
dándole humildes gracias al Señor por haberme dado tanto poder y victoria
sobre las tentaciones en las que tantas veces había caído antes.
Luego comencé a amar al Señor y a deleitarme en volver mi mente al interior,
y a diligentemente esperarlo por medio de la ayuda de Su Santo Espíritu,
mediante el cual poco a poco crecí en experiencia y conocimiento de las cosas de Dios.

¡Oh, cuánto amaba ir a las reuniones!
En realidad, yo anhelaba los días de reuniones,
y cuando estaba ahí me esforzaba por tener mi mente
internamente ejercitada hacia el Señor,
a Quien amaba con todas las fuerzas de mi alma.
¡Oh, cuán cercanos y amados eran para mí los ministros y siervos fieles del Señor,
y los otros Amigos también,
en cuya compañía yo me deleitaba grandemente y amaba
oírlos hablar de las cosas de Dios! ¡Mi mente,
en verdad, había sido completamente apartada de las vanidades,
juegos y pasatiempos del mundo;
todo era nada para mí! Cada vez que podía me iba
a algunos lugares escondidos a esperar en el Señor,
y ahí derramaba mi alma delante de Él con desbordantes lágrimas de alegría,
porque Él había obrado tan misericordiosamente este gran cambio en mí. De hecho,
puedo decir con humilde acción de gracias y alabanza a Su santo nombre,
que a Él le plació aceptar mi tierna ofrenda de corazón quebrantado,
al devolver a veces sobre mi alma dulces réditos de Su divino poder y viva presencia,
para colmar mi espíritu de indecible gozo.

Fui a reuniones, en las que mientras estaba ahí,
una fe viva me ayudaba y una plena certeza se levantaba en mi alma,
de que si esperaba diligentemente con mi mente internamente ejercitada hacia el Señor,
sentiría Su presencia vivificadora; y en verdad, en concordancia con mi fe,
el Señor irrumpía sobre mi espíritu con inefable consuelo.
El recuerdo de esas épocas es renovado dentro de mí en este momento,
por lo que mi alma se derrite de ternura con humilde acción
de gracias y alabanza a Su santa y divina majestad.
En realidad Él me ha mantenido vivo en espíritu hasta la vejez,
para dar este testimonio de Él a partir de mi propia experiencia,
de que Su santa Verdad no envejece como lo hace el vestido.
Pues aunque ahora estoy desgastado en cuerpo,
y debido a una gran debilidad parece estar al borde de la tumba,
con todo puedo decir para alabanza del Señor,
que estoy tan fuerte en Él y en el poder de Su fuerza,
y siento mi espíritu tan celoso por Su santo nombre y testimonio,
como en cualquier momento de mi vida.
¡Por esto,
todo en mi interior magnifica y exalta (con mi boca en el polvo)
el santo y eterno nombre del Señor del cielo y de la tierra,
quien vive por los siglos de los siglos!

Antes de cumplir catorce años de edad,
debido a la obra del Espíritu Santo del Señor en mí,
llegué a experimentar un estado de pureza, santidad e inocencia,
en el que no podía levantarse un pensamiento vano o insensato en mi mente,
sin que la santa luz de Cristo me permitiera verlo y juzgarlo prontamente,
para que aborreciera todos los pensamientos, palabras y actos malvados,
y amara la verdad y la justicia con toda mi alma.
Yo amaba cariñosamente a todos los Amigos fieles y los sentía
tan queridos para mí como mi propia vida;
y en realidad, ellos me amaban al ser conscientes de que yo amaba al Señor.

Aquí, permítanme agregar una advertencia a todos los ministros y ancianos:
Tengan gran cuidado con cualquier libertad indebida de palabras o conducta
delante de aquellos que son jóvenes y tiernos en la Verdad,
estén en la juventud o en la vejez.
Porque los recién convencidos son agudos en su observación,
y si ven algo (ya sea en el uso de más palabras de las que son necesarias,
o en comportamiento,
etc.) que piensan que no está en concordancia con la firmeza a la que conduce la Verdad,
es probable que les estorbe y los confunda.
Vemos que el gran apóstol Pablo era muy tierno con aquellos que eran jóvenes y débiles,
y se negaba a sí mismo cosas lícitas para no ofenderlos diciendo:
"`Todas las cosas me son lícitas, mas no todas convienen.`"

A pesar de que por el poder y Espíritu del Señor había alcanzado un estado de pureza,
¡ay de mí!,
lo perdí de nuevo por falta de verdadera y diligente
vigilancia a la luz y cercano seguimiento a sus guías,
y no por alguna maldad manifiesta que hubiera cometido.
Entre los catorce y quince años me fui haciendo más negligente en esperar en el Señor,
y de ahí, a una cada vez mayor frialdad de mi amor a Él;
de esta manera perdí gradualmente aquel estado tierno
de espíritu que había experimentado anteriormente.
Luego el enemigo de mi alma me tentó con los placeres y vanidades del mundo,
de tal manera, que mi mente fue seducida y atraída hacia ellas,
y las amaba y me deleitaba en ellas.

Entre otras cosas, me incliné a disfrutar de la ropa fina que podía obtener,
de lo cual recuerdo un momento en particular.
Tras obtener un abrigo nuevo muy fino,
el espíritu de orgullo se levantó en mí y pasando por una calle,
(todavía recuerdo el lugar) pensé que yo era alguien (como dice el dicho).
Pero en medio de estos pensamientos vanos e insensatos,
de un momento a otro fui golpeado por el Señor como si me hubiera lanzado una flecha,
y rápidamente pasó por mi mente lo siguiente: "`¡Pobre desgraciado! ¡Jesucristo,
el Señor del cielo y de la tierra era humilde y de corazón bajo,
y Su apariencia humilde en la tierra! Él no era orgulloso ni altivo.
Y tú, pobre gusano, ¿serás altivo y estarás orgulloso de ti mismo o de tus ropas?`"
Estos pensamientos hirieron tanto mi espíritu que volví a mi casa muy triste y abatido,
pero en poco tiempo el sentimiento se desvaneció,
pues los deleites del mundo empezaron a echar raíces en mí y mi mente se fue tras ellos,
de manera que me alejé del Señor.

Doy este testimonio,
de que el adorno del cuerpo con una vestimenta fina y cortes modernos,
así como la extravagancia de los muebles del hogar,
son completamente inconsistentes con la sencillez a la que nos conduce la santa Verdad.
En efecto,
la Verdad sacó a nuestros Amigos ancianos de estas cosas y a testificar contra ellas.
Porque aunque es muy cierto que el orgullo brota primero en el corazón, no obstante,
cuando la mente se deleita en las cosas externas es capturada por ellas,
y la raíz de la vanidad crece internamente cada vez más fuerte.

No le complació al Señor que mi mente se hubiera apartado así de Él,
y provocó que se retirara de mí,
de modo que dejé de disfrutar de la dulzura y consuelo
de Su Santo Espíritu como lo había hecho antes.
Sin embargo, no quitó Su Espíritu de mí,
pero se convirtió en mi juez y condenador por amar aquellas cosas que lo ofendían.
Así que los terrores del Señor con frecuencia se apoderaban de mí,
y podía recordar bien (por la fuerza de mi memoria natural),
cómo había sido antes para mí, cuando tenía el favor del Señor. Sí,
por medio de Su santa Luz vi cómo había perdido la experiencia
viva de la dulzura que había disfrutado con anterioridad,
lo que hizo que lamentara profundamente mi condición.

A partir de esta experiencia he aprendido a entender la vasta diferencia
que existe entre la comprensión natural o memoria,
y el testimonio presente, vivo y palpable de la vida y poder de la Verdad sobre el alma,
por medio de lo cual es mantenida viva para Dios.
Salomón, desde la fuerza de su memoria,
no podía olvidar cuán excelsamente había orado al Señor
por medio del Espíritu Santo en la dedicación del templo,
sin embargo,
después perdió ese sentido vivo y divino cuando se adentró
en la idolatría. El mundo tiene la capacidad anterior,
y por medio de la fuerza de su razón, comprensión y memoria natural, leen,
estudian los idiomas aprendidos y adquieren conocimiento (o más bien, reúnen conceptos),
siendo así preparados y equipados por lo que ellos llaman teología. Pero, ¡ay!,
el verdadero conocimiento de las cosas divinas es otra cosa y es aprendido de otra manera,
es decir, por medio del Espíritu Santo,
y consiste en el disfrute de Su dulce presencia en nuestra alma.
Lo digo en cierta medida por mi propia experiencia,
porque cuando era obediente a Su Luz o Espíritu Santo en mi corazón,
y era enseñado por Él,
me guiaba (aunque era infantil en mi entendimiento
natural) a la montaña sagrada del Sión espiritual,
para el disfrute de Su viva y consoladora presencia.
Pero cuando me negaba a ello, aunque crecía en conocimiento y entendimiento naturales,
perdía mi condición inocente y la comunión espiritual que una vez había tenido,
de modo que, en lugar de que Su Espíritu Santo fuera mi consolador,
se volvía mi juez y condenador.
Estas cosas fluyen vívidamente en mi mente ahora,
y las expongo como un testimonio para el Señor y para la operación de Su Santo Espíritu.

Así permaneció mi condición interna desde los quince a los dieciocho años,
tiempo durante el cual mantuve un carácter bastante
bueno entre los Amigos y los demás. Porque,
a través de la gran misericordia del Señor, nunca caí en ningún mal obvio o escandaloso,
ni mantuve malas compañías,
sino que en general era amado (hasta donde sé) por todos los que me conocían. Sin embargo,
había salido y perdido mi comunión interna y la relación
que había experimentado anteriormente con el Señor.

Esto me lleva a advertirles a todos, sean jóvenes o viejos,
a no estimarse o justificarse a sí mismos basados
en la moralidad de sus conductas y depender de ellas,
como sé que hacen algunos.
Porque aunque un hombre no puede ser un cristiano correcto sin ser una persona moral,
aun así,
el tal puede sostener un carácter moral y estar muy lejos
de ser un verdadero cristiano y aceptable para Dios.
Esto lo puedo decir desde mi propia experiencia.

Cuando tenía casi dieciocho años, le plació al Señor concederme una renovada visitación,
no como aquella repentina y extraordinaria manera de antes, sino de modo gradual.
Él se empezó a levantar y a darme una visión completa y clara de mi condición,
y de cuán alejado estaba de Él en espíritu.
Vi claramente que si continuaba de esa manera,
me volvería más duro y al final estaría arruinado para siempre.
La consciencia de esto me llevó a un gran horror y angustia, con amarga lamentación,
bajo lo cual permanecí un tiempo,
hasta que al Señor misericordiosamente le agradó ablandar un poquito
mi espíritu y ayudarme a orar pidiéndole un corazón arrepentido.
En realidad,
mi desobediencia pasada (al apartarme de Él tan desagradecidamente)
permanecía sobre mi alma como una piedra de molino,
y me llevaba a dolorosa agonía y angustia de espíritu.

Entonces buscaba estar solo, en lugares apartados,
donde con frecuencia derramaba mi alma delante del Señor con muchas lágrimas,
rogando misericordia y perdón. Vi que había incurrido en una gran pérdida,
y que debía desaprender muchas cosas que había aprendido en la noche de
mi apostasía de Él en espíritu (aunque no en principio o profesión),
durante cuyo tiempo la raíz y naturaleza del mal había crecido
fuerte en mí. También vi que nada podía destruir eso sino el hacha,
la espada, el martillo y el fuego de Su Santo Espíritu,
y que yo debía ser regenerado y nacer de nuevo antes
de poder lograr la condición que había perdido.
Todo esto me lo dejó ver muy claramente la luz de Jesús.

¡Entonces, oh entonces, la agonía,
el horror que se apoderó de mi alma! ¡Soy incapaz de expresarlo!
A menudo pensaba que mi condición era diferente a
la de cualquier otra persona en el mundo.
Cuando volvía mi mente al interior,
mi alma parecía como una habitación de dragones que estaban listos para devorarme.
Se presentaban malos pensamientos de muchos tipos,
con tentaciones del maligno a las que nunca antes había sido inducido.
Cuando iba a las reuniones no encontraba reposo en ellas,
porque no podía concentrar mi mente en el Señor. En realidad,
el enemigo parecía rugir sobre mí como si quisiera destruir mi alma,
de modo que estaba casi listo a salir corriendo de las reuniones.
Parecía que el Señor se había retirado por completo de mí,
y que estaba muy lejos como para ayudarme.
Cuando llegaba la noche deseaba que fuera de mañana,
y cuando era de mañana deseaba que fuera el anochecer.
Durante la noche, a menudo me lamentaba y lloraba amargamente,
haciendo que mi almohada se mojara con mis lágrimas.
Mi angustia era tal que si el Señor (en misericordia) no me hubiera compadecido y ayudado,
al concederme una pequeña esperanza y tranquilidad de espíritu,
creo que yo me habría hundido en ella, pues mi miseria era muy grande.
A veces estaba tan abrumado por el dolor,
que casi perdía la esperanza de alguna vez superar mis aflicciones,
pues temía haber sido completamente abandonado.

Después de haber estado así por un tiempo considerable, listo para desmayar en espíritu,
el Señor (en Su propio tiempo, no en el mío,
ni tan poderosamente como yo deseaba) al fin empezó a levantarse
nuevamente con un poquito de la luz de Su rostro,
para tranquilidad de mi angustiada alma; pero esta paz no me duró mucho tiempo,
antes de volver a caer en la misma miseria.
Así fui afligido y sacudido, como en una tempestad,
hasta casi el agotamiento por causa del dolor.
Fui sumergido en el Jordán espiritual (o juicio) una y otra vez, no sólo siete veces,
sino más de setenta veces siete.
¡Oh,
"`el ajenjo y la hiel`" que me fueron dados a beber en ese día! ¡Mi alma
los tiene todavía en la memoria y es humillada dentro de mí! Sin embargo,
con acción de gracias y alabanza al santo nombre del Señor,
Él finalmente me llevó a través de mi angustia y puso mis pies sobre Su roca.

Durante ese tiempo de dolorosa aflicción, leí las Sagradas Escrituras,
especialmente el libro de los Salmos y el del profeta evangélico Isaías,
en los que encontré una gran cantidad de experiencias que
calzaban con mi condición. Y cuando en la lectura de ellas,
el Señor se placía en tocar mi mente por medio de Su Espíritu,
¡cuán consoladoras eran para mí! ¡Oh, cuánto se derretía de ternura mi corazón,
al encontrar que algunas de las experiencias de los
hombres santos concordaban con las mías,
como se refleja una cara en un vidrio,
por lo que se levantó en mí la expectativa de que debía atravesar mis ejercicios,
como ellos atravesaron los suyos!
Pero en otros momentos, cuando el Espíritu del Señor parecía retirarse de mí,
aunque leía las Escrituras y entendía las palabras,
al no ser tocada ni abierta mi mente por el Espíritu del Señor,
no recibía el mismo beneficio ni consuelo.
De esto aprendí por experiencia viva,
que es por y a través de las revelaciones del Espíritu del Señor,
que recibimos el verdadero consuelo o provecho al leer las Sagradas Escrituras.

Esta fue más o menos mi condición,
durante unos dos o tres años. En los momentos que el Señor me permitía orarle, ¡oh,
los fuertes clamores que ascendían!
En realidad, oraba con los más fervientes ruegos del alma,
con desbordantes lágrimas y decía en mi corazón: "`¡Oh, Señor,
no te apartes de mí! ¡Mantenme en esta condición de oración,
no me dejes salir de ella! ¡Guárdeme del mal! ¡Hazme como Tú quieres que sea,
pues sabes que deseo amarte más que a todo el mundo, y con Tu ayuda,
te serviré todos los días de mi vida!`"
Pero no podía permanecer en esta condición, pues no había sido suficientemente purgado,
y tenía que entrar en juicio de nuevo y permanecer bajo Su bautismo espiritual.
Entonces la miseria, el dolor y la lamentación volvían a apoderarse de mí.

Así me sucedió por temporadas, en mi progreso al cielo,
con la diferencia de que los intervalos de tranquilidad se iban haciendo más largos,
durante los cuales estaba listo a decir en mi corazón:
"`Espero que nunca más sea movido.`"
Pero el Señor otra vez se retiraba y escondía Su rostro de mí por un tiempo,
de modo que mi alma se turbaba por ello.
Sin embargo, Su gracia siempre estaba conmigo, como un ancla en el fondo,
y como un monitor, guía y director para preservarme de tropezar con cualquier mal grave.
Pero aunque era preservado de esa manera, aún así,
a menudo ofendía al Señor en asuntos menores por
no mantenerme cerca de la guía de Su luz.
Cuando lo hacía en pensamiento, palabra o acto,
Sus juicios divinos se apoderaban de mi alma y yo me regocijaba en ellos,
y un clamor se levantaba dentro de mí que decía: "`¡Oh, que no se compadezca Tu ojo,
ni muestre misericordia Tu mano,
hasta que el juicio sea llevado a la victoria sobre esta maligna naturaleza
mía!`" En el anochecer yo evocaba en mi mente mis actos del día,
y cuando veía que había hablado más de lo que debía,
o que había usado palabras innecesarias,
o había hecho algo que contristaba al Espíritu del Señor (aunque
tales palabras o actos no fueran condenados por los demás),
¡oh, cómo me inclinaba y me lamentaba al considerar esas cosas,
pidiéndole con humildes oraciones que no me permitiera hacerlas de nuevo!

Recuerdo que en una ocasión, por casi tres meses,
después de cierto grado de tranquilidad,
le plació al Señor retirar la luz de Su rostro y dar la impresión de que me había abandonado,
lo cual me sumió en un dolor inexplicable.
Cuando yo volvía mi mente hacia el interior no encontraba consuelo,
sino que mi cielo era como hierro y mi tierra como bronce por la dureza y esterilidad.
¡En realidad,
estaba embargado de tal agonía de espíritu que mi carne parecía temblar sobre mis huesos!
Yo me examinaba y me preguntaba: "`¿Qué pecado he cometido?
¿Cómo es que he ofendido tanto, que el Señor me ha abandonado por completo?`"
Pero bendito sea Su eterno nombre,
porque Él se levantó de nuevo en Su propio y debido tiempo,
para el gozo y consuelo de mi corazón,
y después vi que esto había sido para probar mi fe y paciencia.

En todo ese tiempo de la más profunda angustia,
nunca le abrí mi mente por completo a nadie,
sino que traté de ocultarles mis ejercicios a todos los mortales.
Yo parecía tan alegre de semblante como podía,
incluso en momentos cuando mi corazón estaba listo a romperse por el dolor,
aunque mi cara a menudo se ponía pálida y algunos
me preguntaban qué me dolía o si estaba enfermo.
Pero yo desestimaba esas preguntas,
aunque creo que algunos Amigos prudentes veían que yo estaba bajo prueba de espíritu.

Soy un tanto extenso en mi relato de estas cosas,
con el único propósito de animar a los viajeros a Sión,
para que aprendan a confiar en el Señor y a no perder la esperanza de
Su misericordia en lo más profundo de sus ejercicios y aflicciones.
Porque por medio y a través de todas estas pruebas,
yo crecí gradualmente en el conocimiento de las cosas de Dios.
Y aunque, cuando estaba bajo lo más profundo de ellas,
no podía ver a través de ellas o el final de las mismas,
después llegué a saber que provenían del Señor. Entendí que este era un tiempo de "`ministración
de condenación,`" para acercarme al Señor al derribar y hacer morir la parte natural
y carnal en mí que se había fortalecido y no podía heredar el reino de Dios.
A través de estos dolorosos ejercicios y al tomar la cruz de Cristo bajo ellos,
mi propia voluntad natural y afectos se rompieron,
y llegué a ser (en cierta medida) como un niño pequeño,
dependiendo del Señor para ser fortalecido y recibir capacidad para hacer Su voluntad.
Por medio del Espíritu del Señor a menudo fui guiado
a negarme a mí mismo las cosas lícitas,
con respecto a cosas como comer, beber y engalanarme,
descubriéndome fuertemente inclinado a ellas.
Además, la santa luz del Señor me reveló abundantes Escrituras que yo no entendía antes,
de modo que he dicho en mi corazón:
"`El mundo cree la verdad de las Sagradas Escrituras por tradición,
pero aquellos que llegan a experimentar la operación de una medida del
mismo Espíritu en sus almas (de quien procedieron las Sagradas Escrituras),
son confirmados por su propia experiencia en la verdad de ellas.`"

Así avanzó la obra en mí, hasta que en el tiempo del Señor pude en alguna medida decir:
'`Él me hizo sacar del pozo de la desesperación, del lodo cenagoso;
puso mis pies (en cierto grado) sobre Su peña, y enderezó mis pasos.`' ¡Oh,
bendito sea Su nombre para siempre!
Aunque la abundancia de mis problemas y ejercicios se desvaneció en pocos años,
a veces podía (cuando estaba habilitado) cantar en mi alma,
tanto de las misericordias del Señor como de Sus juicios.
Sin embargo,
por muchos años enfrenté épocas de dolorosas peleas
de aflicción contra el enemigo de mi alma,
y las enfrento hasta el día de hoy.
Porque, sin duda, en este lado de la tumba,
no hay un estado alcanzable donde no haya necesidad de vigilancia.
Nuestro Señor les dijo a Sus discípulos: "`Velad y orad,
para que no caigáis en tentación.`" A menudo he comparado
el alma del hombre con un jardín;
aunque sea limpiado de malas hierbas, este todavía las produce naturalmente,
y si no es vigilado y mantenido limpio,
las desagradables y molestas malas hierbas brotarán de nuevo.
Y si se les permite crecer,
con seguridad ahogarán la semilla tierna y buena que ha sido sembrada.
"`Engañoso es el corazón más que todas las cosas`" y naturalmente propenso al mal,
y como añade el profeta: "`y perverso.`"
Incluso,
cuando por el poder y espada del Espíritu del Señor muchas
cosas malas puedan parecer completamente destruidas y muertas,
si nosotros no vigilamos diligentemente en la luz,
el enemigo se colará otra vez y revivirá alguna de esas cosas que parecían estar erradicadas,
especialmente las cosas a las que naturalmente estamos más inclinados.

Creo que la parábola de Cristo relacionada con el espíritu
inmundo que fue sacado de un hombre hace alusión a esto.
Pues este espíritu inmundo, después de vagar y no encontrar reposo,
regresó a la misma casa en el corazón del hombre, y al encontrarla barrida y adornada,
tomó otros siete espíritus peores que él y entraron (con
seguridad por falta de vigilancia) y moraron ahí,
y Cristo dice: "`y el postrer estado de aquel hombre viene a ser peor que el primero.`"
Por tanto,
incluso aquel que ha sido en una buena medida limpiado
de su iniquidad y aliviado de su aflicción interna,
puede volverse descuidado y permitir que el enemigo entre de nuevo,
a menos que se mantenga hacia la luz, velando en oración. ¡Oh,
esta vigilancia interna está muy ausente entre muchos del pueblo del Señor!
En consecuencia, muchos no han crecido en la Verdad como podrían haberlo hecho,
sino que se han perdido y algunos han apostatado.
La escuela de Cristo y Sus enseñanzas son internas, como dice el apóstol:
"`Pero lo que se conoce acerca de Dios es evidente dentro de ellos.`"^
footnote:[Romanos 1:19. NBLA, NBLH, ver también la Reina Valera 1602 Purificada.]
Es ahí donde Cristo mismo enseña a Su pueblo.
Cuánto más nos mantengamos vueltos hacia el interior en esta escuela,
más aprenderemos de Cristo.
Cuánto menos nos mantengamos vueltos hacia el interior,
aun cuando estemos involucrados en cosas lícitas, menos aprenderemos de Cristo.
¡Oh, lean, ustedes los que pueden leer en el misterio de vida! ¡No hay seguridad,
ni preservación, ni crecimiento en la Verdad, sino en la verdadera humildad,
manteniéndose vueltos hacia el don del Santo Espíritu de Cristo,
y vigilando continuamente en la luz contra las tentaciones del enemigo!

Por eso, la ferviente respiración de mi alma al Señor es,
que Él misericordiosamente se complazca en guardarme
en vigilancia hasta el último momento de mi vida.
Pues sé muy bien que no puedo guardarme a mí mismo, ni pensar un buen pensamiento,
ni hacer la menor cosa buena, como dijo nuestro bendito Señor: "`Sin mí,
nada podéis hacer.`"
Pero el Santo de Israel da fuerza al pobre y necesitado de espíritu,
por Quien únicamente puede permanecer y no por sí mismo.
¡Qué toda fuerza, majestad, poder y dominio sean atribuidos a Él,
quien vive por los siglos de los siglos!

Habiendo hecho un relato de los varios ejercicios por los que he pasado,
puedo decir desde una cierta y vívida experiencia,
que no es por estar educado en la forma de la verdad, ni por la profesión de la misma,
ni por ser llamado Cuáquero, ni por frecuentar nuestra reuniones religiosas,
y ni siquiera por tener una conducta moral,
lo que nos hará o por lo que seremos aceptables para el Señor,
a menos que también experimentemos la posesión y deleite de la Santa Verdad,
y Su vida y poder en nuestras almas.
Por tanto, deseo fervientemente que los profesantes de la verdad,
y todo los que han sido educados en la forma de ella, no se sientan satisfechos ahí,
sino que vuelvan sus mentes al interior hacia el Señor,
al don de Su Santo Espíritu ahí manifestado,
para que puedan de esa manera ser testigos por experiencia de un crecimiento,
de un progreso, y finalmente, de una herencia en la eterna Verdad del Señor,
la cual ustedes profesan.
Únicamente esto da verdadera aceptación, unión y comunión con Él.

[.asterism]
'''

__Joseph Pike no fue un ministro itinerante en la Sociedad de Amigos,
pero llegó a ser un anciano tan valioso,
que muchos Amigos (incluyendo ministros) regularmente buscaban su sabiduría y consejo.
Estaba inusualmente dotado de un entendimiento de los asuntos y disciplina de la iglesia,
y se aplicaba con toda diligencia al cuidado y fortalecimiento
del cuerpo del Señor. Su más grande preocupación,
tanto por sí mismo como por todos los que habían recibido a Cristo Jesús,
era que todos verdaderamente '`caminaran en Él`' y '`adornaran
la doctrina de Dios nuestro Salvador en todas las cosas.`'__

__Continuó siendo un pilar fiel en la iglesia hasta el final,
escribiendo poco antes de su muerte: "`Todavía estoy en la tierra de los vivos,
pero cuánto tiempo seguiré así, está en Su divina mano, pues estoy débil en el cuerpo,
aunque espero que fuerte en espíritu, esperando ahora mi fin,
hasta el momento en que al Señor le plazca llamarme.
Oro a Él con todas las fuerzas de mi alma que me guarde hasta el final,
y que yo pueda estar verdaderamente preparado para esa segura, aunque incierta hora,
cuando llegue.`"
Él murió en 1729 a los setenta y dos años de edad.__
